database:
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

server:
    port: 8889

auth2:
    githubClientId: c10fd104be25fa95bcc4
    githubClientSecret: 465fafde07d1f100e4a2a6e527737f90099f36d5
logging.level.org.jooq: DEBUG